cd ~/programmercollege/github/homedir/init/
if [ -d "./01.ドキュメント成果物" ]
  then
rm -rf ./01.ドキュメント成果物
fi
mkdir ./01.ドキュメント成果物
mkdir ./02.個人作業及び一時保管用
cd ./01.ドキュメント成果物
mkdir ./00.RFP
mkdir ./01.決裁
cd ./01.決裁
mkdir ./01.プロジェクト決裁
cd ./01.プロジェクト決裁
mkdir ./01.実施決裁
mkdir ./02.契約決裁
mkdir ./03.変更決裁
mkdir ./04.遡及決裁
cd ../
mkdir ./02.タスク決裁
cd ./02.タスク決裁
mkdir ./01.実施兼契約決裁
mkdir ./02.変更決裁
mkdir ./03.遡及決裁
cd ../../
mkdir ./02.要件定義
cd ./02.要件定義
mkdir ./01.要求分析
mkdir ./02.画面調査及び機能調査
cd ../
mkdir ./03.方式設計
cd ./03.方式設計
mkdir ./01.インフラ設計
mkdir ./02.開発環境
mkdir ./03.開発スケジュール
mkdir ./04.システム概要
mkdir ./05.開発方式
cd ../
mkdir ./04.画面設計
cd ./04.画面設計
mkdir ./01.PC向け
cd ./01.PC向け
mkdir ./01.画面遷移図
mkdir ./02.画面設計書
cd ../
mkdir ./02.SmartPhone向け
cd ./02.SmartPhone向け
mkdir ./01.画面遷移図
mkdir ./02.画面設計書
cd ../../
mkdir ./05.DB設計
cd ./05.DB設計
mkdir ./01.DB設計書
mkdir ./02.ER図
cd ../
mkdir ./06.機能設計
cd ./06.機能設計
touch ./ここにはJavaDocで生成した最終ドキュメントを保管してください
cd ../
mkdir ./07.実装
mkdir ./08.単体試験
cd ./08.単体試験
mkdir ./01.単体試験書
mkdir ./02.単体試験書結果及び実施報告書
cd ./02.単体試験書結果及び実施報告書
mkdir ./01.単体試験書結果
mkdir ./02.単体試験実施報告書
cd ../..
mkdir ./09.結合試験
cd ./09.結合試験
mkdir ./01.シナリオ試験
cd ./01.シナリオ試験
mkdir ./01.結合シナリオ試験書
mkdir ./02.結合シナリオ試験書結果及び実施報告書
cd ../
mkdir ./02.アドホック試験
cd ./02.アドホック試験
mkdir ./01.結合アドホック試験実施結果
mkdir ./02.結合アドホック試験修正項目書（原本）
mkdir ./03.結合アドホック試験修正項目書（結果）
mkdir ./04.結合アドホック試験実施報告書
cd ../
mkdir ./03.結合試験実施報告書
cd ../
mkdir ./10.結合試験判定会資料
mkdir ./11.総合試験
cd ./11.総合試験
mkdir ./01.シナリオ試験
cd ./01.シナリオ試験
mkdir ./01.総合シナリオ試験項目書（原本）
mkdir ./02.総合シナリオ試験項目書（結果）
mkdir ./03.総合シナリオ試験実施報告書
cd ../
mkdir ./02.アドホック試験
cd ./02.アドホック試験
mkdir ./01.総合アドホック試験実施結果
mkdir ./02.総合アドホック試験修正項目書（原本）
mkdir ./03.総合アドホック試験修正項目書（結果）
mkdir ./04.総合アドホック試験実施報告書
cd ../
mkdir ./03.総合試験実施報告書
cd ../
mkdir ./12.総合試験判定会資料
mkdir ./13.リリース判定会資料及びリリース関連書類
mkdir ./14.納品向け補足資料
mkdir ./15.議事録
touch ./フォルダ構成は変更しないでください
