set names utf8;
set foreign_key_checks=0;
drop database if exists kintai;
create database if not exists kintai;
use kintai;


drop table if exists kintai.attendance_inoue;
drop table if exists kintai.attendance_igarashi;
drop table if exists kintai.attendance_takagi;
drop table if exists kintai.attendance_sogo;
drop table if exists kintai.attendance_ebata;
drop table if exists kintai.attendance_yokoyama;
drop table if exists kintai.attendance_sakai;
drop table if exists kintai.attendance_suzuki;
drop table if exists kintai.attendance_wakamatsu;
drop table if exists kintai.attendance_honma;
drop table if exists kintai.attendance_isobe;
drop table if exists kintai.attendance_yamanobe;
drop table if exists kintai.attendance_kitahara;
drop table if exists kintai.attendance_takeuchi;
drop table if exists kintai.attendance_mitsuda;
drop table if exists kintai.attendance_watanabe;
drop table if exists kintai.attendance_wada;
drop table if exists kintai.attendance_hosoya;
drop table if exists kintai.attendance_ikeda;
drop table if exists kintai.attendance_kuriya;
drop table if exists kintai.attendance_dai;
drop table if exists kintai.attendance_ozaki;
drop table if exists kintai.attendance_isa;
drop table if exists kintai.attendance_hiayama;
drop table if exists kintai.attendance_yamashita;
drop table if exists kintai.attendance_kuga;
drop table if exists kintai.attendance_nakashima;


create table if not exists kintai.attendance_inoue (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_igarashi (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_takagi (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_sogo (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_ebata (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_yokoyama (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_sakai (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_suzuki (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_wakamatsu (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_honma (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_isobe (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_yamanobe (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_kitahara (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_takeuchi (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_mitsuda (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_watanabe (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_wada (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_hosoya (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_ikeda (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_kuriya (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_dai (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_ozaki (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_isa (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_hiayama (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_yamashita (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_kuga (mmdd date,attendance datetime,away datetime);
create table if not exists kintai.attendance_nakashima (mmdd date,attendance datetime,away datetime);
