cd ..
sudo git clone https://github.com/takumainoue/init
sudo git clone https://github.com/takumainoue/JissenKadai5
sudo git clone https://github.com/takumainoue/JissenKadai4
sudo git clone https://github.com/takumainoue/.dropbox-internousdev
sudo git clone https://github.com/takumainoue/.dropbox-takumainoue7
sudo git clone https://github.com/takumainoue/.dropbox-internousdev03
sudo git clone https://github.com/takumainoue/.dropbox-internousdev02
sudo git clone https://github.com/takumainoue/.dropbox-internousdev01
sudo git clone https://github.com/takumainoue/.sh
sudo git clone https://github.com/takumainoue/release-internousdevmaster
sudo git clone https://github.com/takumainoue/release-internousdevwork
sudo git clone https://github.com/takumainoue/.bat
sudo git clone https://github.com/takumainoue/openconnect
sudo git clone https://github.com/takumainoue/.ssh
sudo git clone https://github.com/takumainoue/.sql
sudo git clone https://github.com/takumainoue/.zsh
sudo git clone https://github.com/takumainoue/.war
sudo git clone https://github.com/takumainoue/.emacs.d
sudo git clone https://github.com/takumainoue/.internousdb
sudo git clone https://github.com/takumainoue/JissenKadai2
sudo git clone https://github.com/takumainoue/JissenKadai3
sudo git clone https://github.com/takumainoue/workspace
sudo git clone https://github.com/takumainoue/internousdev-com
sudo git clone https://github.com/takumainoue/internous-database-connector
sudo git clone https://github.com/takumainoue/internous-rateexchanger
sudo git clone https://github.com/takumainoue/internous-creditcard
sudo git clone https://github.com/takumainoue/JissenKadai1_2
sudo git clone https://github.com/takumainoue/jissenKadai1_1
sudo git clone https://github.com/takumainoue/KisoKadai3
sudo git clone https://github.com/takumainoue/KisoKadai2
sudo git clone https://github.com/takumainoue/KisoKadai1
sudo git clone https://github.com/takumainoue/project-docs
sudo git clone https://github.com/takumainoue/eclipse
sudo git clone https://github.com/takumainoue/struts2
sudo git clone https://github.com/takumainoue/prototype
sudo git clone https://github.com/takumainoue/gsession
sudo git clone https://github.com/takumainoue/jenkins
sudo git clone https://github.com/takumainoue/tomcat8
sudo git clone https://github.com/takumainoue/dotfiles

sudo chown inouetakuma ./*
